package cn.zhangtianxiao.jf_example._model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_article", "id", Article.class);
		arp.addMapping("t_img", "id", Img.class);
		arp.addMapping("t_session", "id", Session.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_user_like", "id", UserLike.class);
	}
}

