package cn.zhangtianxiao.jf_example._model;

import cn.zhangtianxiao.jf_example._model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article().dao();
}
