package cn.zhangtianxiao.jf_example._model;

import cn.zhangtianxiao.jf_example._model.base.BaseImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Img extends BaseImg<Img> {
	public static final Img dao = new Img().dao();
}
