package cn.zhangtianxiao.jf_example._model;

import cn.zhangtianxiao.jf_example._model.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {
	public static final Session dao = new Session().dao();
}
