package cn.zhangtianxiao.jf_example._model;

import cn.zhangtianxiao.jf_example._model.base.BaseUserLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLike extends BaseUserLike<UserLike> {
	public static final UserLike dao = new UserLike().dao();
}
