package cn.zhangtianxiao.jf_example._model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImg<M extends BaseImg<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setUploadUserId(java.lang.String uploadUserId) {
		set("upload_user_id", uploadUserId);
		return (M)this;
	}

	public java.lang.String getUploadUserId() {
		return get("upload_user_id");
	}

	public M setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
		return (M)this;
	}

	public java.lang.String getFilePath() {
		return get("file_path");
	}

	public M setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
		return (M)this;
	}

	public java.util.Date getUploadTime() {
		return get("upload_time");
	}

}
