package cn.zhangtianxiao.jf_example._model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public M setPassWord(java.lang.String passWord) {
		set("pass_word", passWord);
		return (M)this;
	}

	public java.lang.String getPassWord() {
		return get("pass_word");
	}

	public M setHeadShot(java.lang.String headShot) {
		set("head_shot", headShot);
		return (M)this;
	}

	public java.lang.String getHeadShot() {
		return get("head_shot");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setRegistIp(java.lang.String registIp) {
		set("regist_ip", registIp);
		return (M)this;
	}

	public java.lang.String getRegistIp() {
		return get("regist_ip");
	}

	public M setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
		return (M)this;
	}

	public java.lang.String getLastLoginIp() {
		return get("last_login_ip");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}

	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public M setState(java.lang.Long state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Long getState() {
		return get("state");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}

	public java.lang.String getAccount() {
		return get("account");
	}

}
